In [1]:
##########################################################################
# Created on Sat Nov 22 13:13:45 2021                                    #
# Python for Financial Analysis and Risk Management                      #
# @author: Meng Lipeng (FRM, CFA)                                        #
##########################################################################

# 9.3.2.Cashflow of fixed-to-fixed ccyswap

In [2]:
def CCS_fixed_cashflow(La,Lb,Ra_fix,Rb_fix,m,T,trader,par):
    '''Define a function to calculate cashflow of fixed-to-fixed ccyswap.
    La:notional amount of currency A
    Lb:notional amount of currency B
    Ra_fix:fixed rate of currency A
    Rb_fix:fixed rate of currency B
    m:payment frequency per year
    T:tenor of contract
    trader:'A' indicates to calculate cashflow of side A, otherwise side B
    par:'La' indicates cashflow based on La, otherwise Lb'''
    import numpy as np
    cashflow=np.zeros(m*T+1)
    if par=='La':
        cashflow[0]=-La
        cashflow[1:-1]=Ra_fix*La/m
        cashflow[-1]=(Ra_fix/m+1)*La
        if trader=='A':
            return cashflow
        else:
            return -cashflow
    else:
        cashflow[0]=Lb
        cashflow[1:-1]=-Rb_fix*Lb/m
        cashflow[-1]=-(Rb_fix/m+1)*Lb
        if trader=='A':
            return cashflow
        else:
            return -cashflow

In [4]:
par_CNY=6.4e8
par_USD=1e8
rate_CNY=0.02
rate_USD=0.01
M=2
tenor=5

cashflow_Ebank_CNY=CCS_fixed_cashflow(La=par_CNY,Lb=par_USD,Ra_fix=rate_CNY,Rb_fix=rate_USD,m=M,T=tenor,trader='A',par='La')
cashflow_Ebank_USD=CCS_fixed_cashflow(La=par_CNY,Lb=par_USD,Ra_fix=rate_CNY,Rb_fix=rate_USD,m=M,T=tenor,trader='A',par='Lb')
print('Cashflow for E bank based on CNY is\n',cashflow_Ebank_CNY)
print('Cashflow for E bank based on USD is\n',cashflow_Ebank_USD)

Cashflow for E bank based on CNY is
 [-6.400e+08  6.400e+06  6.400e+06  6.400e+06  6.400e+06  6.400e+06
  6.400e+06  6.400e+06  6.400e+06  6.400e+06  6.464e+08]
Cashflow for E bank based on USD is
 [ 1.000e+08 -5.000e+05 -5.000e+05 -5.000e+05 -5.000e+05 -5.000e+05
 -5.000e+05 -5.000e+05 -5.000e+05 -5.000e+05 -1.005e+08]


In [5]:
cashflow_Fbank_CNY=CCS_fixed_cashflow(La=par_CNY,Lb=par_USD,Ra_fix=rate_CNY,Rb_fix=rate_USD,m=M,T=tenor,trader='B',par='La')
cashflow_Fbank_USD=CCS_fixed_cashflow(La=par_CNY,Lb=par_USD,Ra_fix=rate_CNY,Rb_fix=rate_USD,m=M,T=tenor,trader='B',par='Lb')
print('Cashflow for F bank based on CNY is\n',cashflow_Fbank_CNY)
print('Cashflow for F bank based on USD is\n',cashflow_Fbank_USD)

Cashflow for F bank based on CNY is
 [ 6.400e+08 -6.400e+06 -6.400e+06 -6.400e+06 -6.400e+06 -6.400e+06
 -6.400e+06 -6.400e+06 -6.400e+06 -6.400e+06 -6.464e+08]
Cashflow for F bank based on USD is
 [-1.000e+08  5.000e+05  5.000e+05  5.000e+05  5.000e+05  5.000e+05
  5.000e+05  5.000e+05  5.000e+05  5.000e+05  1.005e+08]


# 9.3.3.Cashflow of fixed-to-floating ccyswap

In [8]:
def CCS_fixflt_cashflow(La,Lb,Ra_fix,Rb_flt,m,T,trader,par):
    '''Define a function to calculate cashflow of fixed-to-floating ccyswap.
    La:notional amount of currency A
    Lb:notional amount of currency B
    Ra_fix:fixed rate of currency A
    Rb_flt:floating rate of currency B, input as array
    m:payment frequency per year
    T:tenor of contract
    trader:'A' indicates to calculate cashflow of side A, otherwise side B
    par:'La' indicates cashflow based on La, otherwise Lb'''
    import numpy as np
    cashflow=np.zeros(m*T+1)
    if par=='La':
        cashflow[0]=-La
        cashflow[1:-1]=Ra_fix*La/m
        cashflow[-1]=(Ra_fix/m+1)*La
        if trader=='A':
            return cashflow
        else:
            return -cashflow
    else:
        cashflow[0]=Lb
        cashflow[1:-1]=-Rb_flt[:-1]*Lb/m
        cashflow[-1]=-(Rb_flt[-1]/m+1)*Lb
        if trader=='A':
            return cashflow
        else:
            return -cashflow

# 9.3.4.Cashflow of floating-to-floating ccyswap

In [14]:
def CCS_float_cashflow(La,Lb,Ra_flt,Rb_flt,m,T,trader,par):
    '''Define a function to calculate cashflow of floating-to-floating ccyswap.
    La:notional amount of currency A
    Lb:notional amount of currency B
    Ra_flt:floating rate of currency A, input as array
    Rb_flt:floating rate of currency B, input as array
    m:payment frequency per year
    T:tenor of contract
    trader:'A' indicates to calculate cashflow of side A, otherwise side B
    par:'La' indicates cashflow based on La, otherwise Lb'''
    import numpy as np
    cashflow=np.zeros(m*T+1)
    if par=='La':
        cashflow[0]=-La
        cashflow[1:-1]=Ra_flt[:-1]*La/m
        cashflow[-1]=(Ra_flt[-1]/m+1)*La
        if trader=='A':
            return cashflow
        else:
            return -cashflow
    else:
        cashflow[0]=Lb
        cashflow[1:-1]=-Rb_flt[:-1]*Lb/m
        cashflow[-1]=-(Rb_flt[-1]/m+1)*Lb
        if trader=='A':
            return cashflow
        else:
            return -cashflow

In [10]:
import numpy as np

par_CNY1=6.9e8
par_USD=1e8
par_CNY2=1.8e8
par_HKD=2e8

M1=2
M2=1

T1=3
T2=4

rate_fix=0.03
Libor=np.array([0.012910,0.014224,0.016743,0.024744,0.028946,0.025166])
Shibor=np.array([0.031600,0.046329,0.035270,0.031220])
Hibor=np.array([0.013295,0.015057,0.026593,0.023743])

cashflow_Gbank_CNY1=CCS_fixflt_cashflow(La=par_CNY1,Lb=par_USD,Ra_fix=rate_fix,Rb_flt=Libor,m=M1,T=T1,trader='A',par='La')
cashflow_Gbank_USD=CCS_fixflt_cashflow(La=par_CNY1,Lb=par_USD,Ra_fix=rate_fix,Rb_flt=Libor,m=M1,T=T1,trader='A',par='Lb')
print('Cashflow for G bank based on CNY is\n',cashflow_Gbank_CNY1)
print('Cashflow for G bank based on USD is\n',cashflow_Gbank_USD)

Cashflow for G bank based on CNY is
 [-6.9000e+08  1.0350e+07  1.0350e+07  1.0350e+07  1.0350e+07  1.0350e+07
  7.0035e+08]
Cashflow for G bank based on USD is
 [ 1.000000e+08 -6.455000e+05 -7.112000e+05 -8.371500e+05 -1.237200e+06
 -1.447300e+06 -1.012583e+08]


In [11]:
cashflow_Hbank_CNY1=CCS_fixflt_cashflow(La=par_CNY1,Lb=par_USD,Ra_fix=rate_fix,Rb_flt=Libor,m=M1,T=T1,trader='B',par='La')
cashflow_Hbank_USD=CCS_fixflt_cashflow(La=par_CNY1,Lb=par_USD,Ra_fix=rate_fix,Rb_flt=Libor,m=M1,T=T1,trader='B',par='Lb')
print('Cashflow for H bank based on CNY is\n',cashflow_Hbank_CNY1)
print('Cashflow for H bank based on USD is\n',cashflow_Gbank_USD)

Cashflow for H bank based on CNY is
 [ 6.9000e+08 -1.0350e+07 -1.0350e+07 -1.0350e+07 -1.0350e+07 -1.0350e+07
 -7.0035e+08]
Cashflow for H bank based on USD is
 [ 1.000000e+08 -6.455000e+05 -7.112000e+05 -8.371500e+05 -1.237200e+06
 -1.447300e+06 -1.012583e+08]


In [15]:
cashflow_Gbank_CNY2=CCS_float_cashflow(La=par_CNY2,Lb=par_HKD,Ra_flt=Shibor,Rb_flt=Hibor,m=M2,T=T2,trader='A',par='La')
cashflow_Gbank_HKD=CCS_float_cashflow(La=par_CNY2,Lb=par_HKD,Ra_flt=Shibor,Rb_flt=Hibor,m=M2,T=T2,trader='A',par='Lb')
print('Cashflow for G bank based on CNY is\n',cashflow_Gbank_CNY2)
print('Cashflow for G bank based on HKD is\n',cashflow_Gbank_HKD)

Cashflow for G bank based on CNY is
 [-1.800000e+08  5.688000e+06  8.339220e+06  6.348600e+06  1.856196e+08]
Cashflow for G bank based on HKD is
 [ 2.000000e+08 -2.659000e+06 -3.011400e+06 -5.318600e+06 -2.047486e+08]


In [16]:
cashflow_Ibank_CNY2=CCS_float_cashflow(La=par_CNY2,Lb=par_HKD,Ra_flt=Shibor,Rb_flt=Hibor,m=M2,T=T2,trader='B',par='La')
cashflow_Ibank_HKD=CCS_float_cashflow(La=par_CNY2,Lb=par_HKD,Ra_flt=Shibor,Rb_flt=Hibor,m=M2,T=T2,trader='B',par='Lb')
print('Cashflow for I bank based on CNY is\n',cashflow_Ibank_CNY2)
print('Cashflow for I bank based on HKD is\n',cashflow_Ibank_HKD)

Cashflow for I bank based on CNY is
 [ 1.800000e+08 -5.688000e+06 -8.339220e+06 -6.348600e+06 -1.856196e+08]
Cashflow for I bank based on HKD is
 [-2.000000e+08  2.659000e+06  3.011400e+06  5.318600e+06  2.047486e+08]


# 9.3.5.Equivalence and valuation

For trade side of A,
$$V_{CS}=B_A-B_BE\tag{9-12}$$
For trade side of B
$$V_{CS}=B_B-\frac{B_A}{E}\tag{9-13}$$
where,\
$E$:spot FX rate

**Fixed-to-fixed ccyswap valuation**
$$B_{A}=\left(\frac{R_A}{m}\sum_{i=1}^{N}e^{-y_i^A\tilde{t}_i}+e^{-y_N^A\tilde{T}}\right)L_A\tag{9-14}$$
$$B_{B}=\left(\frac{R_B}{m}\sum_{i=1}^{N}e^{-y_i^B\tilde{t}_i}+e^{-y_N^B\tilde{T}}\right)L_B\tag{9-15}$$
where,\
$\tilde{t}_i$:valuation date to next ith payment date\
$\tilde{T}$:contract remaining tenor in year\
$y_i^A$:Discount rate of currency A at $t_i$ (continuous compound)\
$y_i^B$:Discount rate of currency B at $t_i$ (continuous compound)

Combine (9-12), (9-14) and (9-15), for trade side of A,
$$V_{CS}=B_A-B_BE=\left(\frac{R_A}{m}\sum_{i=1}^{N}e^{-y_i^A\tilde{t}_i}+e^{-y_N^A\tilde{T}}\right)L_A-\left(\frac{R_B}{m}\sum_{i=1}^{N}e^{-y_i^B\tilde{t}_i}+e^{-y_N^B\tilde{T}}\right)L_BE\tag{9-16}$$
for trade side of B,
$$V_{CS}=B_B-\frac{B_A}{E}=\left(\frac{R_B}{m}\sum_{i=1}^{N}e^{-y_i^B\tilde{t}_i}+e^{-y_N^B\tilde{T}}\right)L_B-\left(\frac{R_A}{m}\sum_{i=1}^{N}e^{-y_i^A\tilde{t}_i}+e^{-y_N^A\tilde{T}}\right)\frac{L_A}{E}\tag{9-17}$$

**Fixed-to-floating ccyswap valuation**
$$B_{B}=\left(\frac{R_{B}}{m}+1\right)e^{-y_1^B\tilde{t}_1}L_B\tag{9-18}$$
where,\
$R_B$:next payment floating rate

Combine (9-12), (9-14) and (9-18), for trade side of A,
$$V_{CS}=B_A-B_BE=\left(\frac{R_A}{m}\sum_{i=1}^{N}e^{-y_i^A\tilde{t}_i}+e^{-y_N^A\tilde{T}}\right)L_A-\left(\frac{R_{B}}{m}+1\right)e^{-y_1^B\tilde{t}_1}L_BE\tag{9-19}$$
for trade side of B,
$$V_{CS}=B_B-\frac{B_A}{E}=\left(\frac{R_{B}}{m}+1\right)e^{-y_1^B\tilde{t}_1}L_B-\left(\frac{R_A}{m}\sum_{i=1}^{N}e^{-y_i^A\tilde{t}_i}+e^{-y_N^A\tilde{T}}\right)\frac{L_A}{E}\tag{9-20}$$

**Floating-to-floating ccyswap valuation**
for trade side of A,
$$V_{CS}=B_A-B_BE=\left(\frac{R_{A}}{m}+1\right)e^{-y_1^A\tilde{t}_1}L_A-\left(\frac{R_{B}}{m}+1\right)e^{-y_1^B\tilde{t}_1}L_BE\tag{9-21}$$
for trade side of B,
$$V_{CS}=B_B-\frac{B_A}{E}=\left(\frac{R_{B}}{m}+1\right)e^{-y_1^B\tilde{t}_1}L_B-\left(\frac{R_{A}}{m}+1\right)e^{-y_1^A\tilde{t}_1}\frac{L_A}{E}\tag{9-22}$$

**Pricing fixed rate**
$$R=\frac{m(1-q_N)}{\sum_{i=1}^Nq_i}\tag{9-23}$$
where,\
$q_i=e^{-y_it_i}$:discount factor at $t_i$

In [17]:
def CCS_value(types,La,Lb,Ra,Rb,ya,yb,E,m,t,trader):
    '''Define a function for ccyswap valuation.
    types:type of ccyswap. 'fixed-fixed','floating-floating',otherwise fixed-to-floating
    La:notional amount for currency A
    Lb:notional amount for currency B
    Ra:rate of currency A
    Rb:rate of currency B
    ya:continuous compound zero rate of currency A(discount rate), input as array
    yb:continuous compound zero rate of currency B(discount rate), input as array
    E:spot FX rate(A/B) at valuation date
    m:payment frequency per year
    t:valution date to next ith payment date, input as array
    trader:'A' indicates to trade side A, otherwise trade side B'''
    from numpy import exp
    
    if types=='fixed-fixed':
        Bond_A=(Ra*sum(exp(-ya*t))/m+exp(-ya[-1]*t[-1]))*La
        Bond_B=(Rb*sum(exp(-yb*t))/m+exp(-yb[-1]*t[-1]))*Lb
    elif types=='floating-floating':
        Bond_A=(Ra/m+1)*exp(-ya[0]*t[0])*La
        Bond_B=(Rb/m+1)*exp(-yb[0]*t[0])*Lb
    else:
        Bond_A=(Ra*sum(exp(-ya*t))/m+exp(-ya[-1]*t[-1]))*La
        Bond_B=(Rb/m+1)*exp(-yb[0]*t[0])*Lb
        
    if trader=='A':
        swap_value=Bond_A-Bond_B*E
    else:
        swap_value=Bond_B-Bond_A/E
    
    return swap_value

In [18]:
import utils

y_CNY_Apr1=np.array([0.016778,0.019062,0.019821])
M=1
tenor=3

rate_CNY=utils.swap_rate(m=M,y=y_CNY_Apr1,T=tenor)
print('Fixed rate of CNY is ',round(rate_CNY,4))

Fixed rate of CNY is  0.02


In [20]:
import datetime as dt

FX_Apr1=7.0771
par_USD=1e8
par_CNY=par_USD*FX_Apr1

Libor_Apr1=0.010024

y_CNY_Jun18=np.array([0.021156,0.023294,0.023811])
y_USD_Jun18=np.array([0.0019,0.0019,0.0022])
FX_Jun18=7.0903

y_CNY_Jul20=np.array([0.022540,0.024251,0.025256])
y_USD_Jul20=np.array([0.0014,0.0016,0.0018])
FX_Jul20=6.9928

t0=dt.datetime(2020,4,1)
t1=dt.datetime(2020,6,18)
t2=dt.datetime(2020,7,20)

t1_list=np.arange(1,tenor+1)-(t1-t0).days/365
t1_list

array([0.78630137, 1.78630137, 2.78630137])

In [21]:
t2_list=np.arange(1,tenor+1)-(t2-t0).days/365
t2_list

array([0.69863014, 1.69863014, 2.69863014])

In [23]:
value_CNY_Jun18=CCS_value(types='fixed-floating',La=par_CNY,Lb=par_USD,Ra=rate_CNY,Rb=Libor_Apr1,ya=y_CNY_Jun18,yb=y_USD_Jun18,E=FX_Jun18,m=M,t=t1_list,trader='A')
value_USD_Jun18=CCS_value(types='fixed-floating',La=par_CNY,Lb=par_USD,Ra=rate_CNY,Rb=Libor_Apr1,ya=y_CNY_Jun18,yb=y_USD_Jun18,E=FX_Jun18,m=M,t=t1_list,trader='B')

value_CNY_Jul20=CCS_value(types='fixed-floating',La=par_CNY,Lb=par_USD,Ra=rate_CNY,Rb=Libor_Apr1,ya=y_CNY_Jul20,yb=y_USD_Jul20,E=FX_Jul20,m=M,t=t2_list,trader='A')
value_USD_Jul20=CCS_value(types='fixed-floating',La=par_CNY,Lb=par_USD,Ra=rate_CNY,Rb=Libor_Apr1,ya=y_CNY_Jul20,yb=y_USD_Jul20,E=FX_Jul20,m=M,t=t2_list,trader='B')

print('Ccyswap value(CNY) for Bank J at 2020/06/18 is ',round(value_CNY_Jun18,2))
print('Ccyswap value(USD) for Bank K at 2020/06/18 is ',round(value_USD_Jun18,2))

print('Ccyswap value(CNY) for Bank J at 2020/07/20 is ',round(value_CNY_Jul20,2))
print('Ccyswap value(USD) for Bank K at 2020/07/20 is ',round(value_USD_Jul20,2))

Ccyswap value(CNY) for Bank J at 2020/06/18 is  -12068317.38
Ccyswap value(USD) for Bank K at 2020/06/18 is  1702088.4
Ccyswap value(CNY) for Bank J at 2020/07/20 is  -3804108.71
Ccyswap value(USD) for Bank K at 2020/07/20 is  544003.65
