In [1]:
##########################################################################
# Created on Sat Otc 24 16:39:25 2021                                    #
# Python for Financial Analysis and Risk Management                      #
# @author: Meng Lipeng (FRM, CFA)                                        #
##########################################################################

# 2.2.1.Structure of array

## 1.Direct input

In [3]:
import numpy as np
weight_array1=np.array([0.15, 0.2, 0.25, 0.4])
type(weight_array1)

numpy.ndarray

In [4]:
weight_array1.shape

(4,)

In [8]:
return_array1=np.array([[-0.035099,0.017230,-0.003450,-0.024551,0.039368],
                        [-0.013892,0.024334,-0.033758,0.014622,0.000128],
                        [0.005848,-0.002907,0.005831,0.005797,-0.005764],
                        [0.021242,0.002133,-0.029803,-0.002743,-0.014301]])

In [9]:
return_array1

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368],
       [-0.013892,  0.024334, -0.033758,  0.014622,  0.000128],
       [ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242,  0.002133, -0.029803, -0.002743, -0.014301]])

In [7]:
return_array1.shape

(4, 5)

## 2.Transfer from list

In [10]:
weight_list=[0.15,0.20,0.25,0.40]
weight_array2=np.array(weight_list)
weight_array2

array([0.15, 0.2 , 0.25, 0.4 ])

In [11]:
return_list=[-0.035099,0.017230,-0.003450,-0.024551,0.039368,-0.013892,0.024334,-0.033758,0.014622,0.000128,0.005848,-0.002907,0.005831,0.005797,-0.005764,0.021242,0.002133,-0.029803,-0.002743,-0.014301]

In [12]:
return_array2=np.array(return_list).reshape(4,5)
return_array2

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368],
       [-0.013892,  0.024334, -0.033758,  0.014622,  0.000128],
       [ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242,  0.002133, -0.029803, -0.002743, -0.014301]])

In [13]:
return_array3=return_array2.ravel() #2dim array -> 1dim array
return_array3

array([-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368, -0.013892,
        0.024334, -0.033758,  0.014622,  0.000128,  0.005848, -0.002907,
        0.005831,  0.005797, -0.005764,  0.021242,  0.002133, -0.029803,
       -0.002743, -0.014301])

## 3.Attribute

In [14]:
# View the dimensions of an array

In [15]:
weight_array1.ndim

1

In [16]:
return_array1.ndim

2

In [18]:
# View the number of elements in an array

In [17]:
weight_array1.size

4

In [19]:
return_array1.size

20

In [22]:
# View the type of elements in an array 

In [20]:
weight_array1.dtype

dtype('float64')

In [21]:
return_array1.dtype

dtype('float64')

# 2.2.2.Special array

## 1.Integer sequence

In [24]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b=np.arange(1,18,3)
b

array([ 1,  4,  7, 10, 13, 16])

## 2.Arithmetic sequence

In [31]:
c=np.linspace(0,100,51)
c

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

In [32]:
len(c)

51

## 3.Zero array

In [34]:
zero_array1=np.zeros(8)
zero_array1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
zero_array2=np.zeros((5,7))
zero_array2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [38]:
zero_weight=np.zeros_like(weight_array1)
zero_weight

array([0., 0., 0., 0.])

In [39]:
zero_return=np.zeros_like(return_array1)
zero_return

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 4.One array

In [40]:
one_weight=np.ones_like(weight_array1)
one_weight

array([1., 1., 1., 1.])

In [41]:
one_return=np.ones_like(return_array1)
one_return

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 5.Identity matrix

In [42]:
d=np.eye(6)
d

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])