In [1]:
##########################################################################
# Created on Sat Otc 24 20:42:25 2021                                    #
# Python for Financial Analysis and Risk Management                      #
# @author: Meng Lipeng (FRM, CFA)                                        #
##########################################################################

# 2.3.1.Indexing

In [3]:
import numpy as np
return_array1=np.array([[-0.035099,0.017230,-0.003450,-0.024551,0.039368],
                        [-0.013892,0.024334,-0.033758,0.014622,0.000128],
                        [0.005848,-0.002907,0.005831,0.005797,-0.005764],
                        [0.021242,0.002133,-0.029803,-0.002743,-0.014301]])

In [5]:
return_array1[1,3] #row 2,column 4

0.014622

In [6]:
np.where(return_array1>0.014) #First array is row's index, Second array is column's index

(array([0, 0, 1, 1, 3]), array([1, 4, 1, 3, 0]))

# 2.3.2.Slicing

In [7]:
return_array1[1:3, 1:4] #row(2~3)column(2~4)

array([[ 0.024334, -0.033758,  0.014622],
       [-0.002907,  0.005831,  0.005797]])

In [8]:
return_array1[1] #row(2)

array([-0.013892,  0.024334, -0.033758,  0.014622,  0.000128])

In [9]:
return_array1[:,2] #column(3)

array([-0.00345 , -0.033758,  0.005831, -0.029803])

# 2.3.3.Sorting

In [10]:
np.sort(return_array1,axis=0) #order by column

array([[-0.035099, -0.002907, -0.033758, -0.024551, -0.014301],
       [-0.013892,  0.002133, -0.029803, -0.002743, -0.005764],
       [ 0.005848,  0.01723 , -0.00345 ,  0.005797,  0.000128],
       [ 0.021242,  0.024334,  0.005831,  0.014622,  0.039368]])

In [11]:
np.sort(return_array1,axis=1) #order by row

array([[-0.035099, -0.024551, -0.00345 ,  0.01723 ,  0.039368],
       [-0.033758, -0.013892,  0.000128,  0.014622,  0.024334],
       [-0.005764, -0.002907,  0.005797,  0.005831,  0.005848],
       [-0.029803, -0.014301, -0.002743,  0.002133,  0.021242]])

In [16]:
np.sort(return_array1) #default:axis=1

array([[-0.035099, -0.024551, -0.00345 ,  0.01723 ,  0.039368],
       [-0.033758, -0.013892,  0.000128,  0.014622,  0.024334],
       [-0.005764, -0.002907,  0.005797,  0.005831,  0.005848],
       [-0.029803, -0.014301, -0.002743,  0.002133,  0.021242]])

# 2.3.4.Combining

### Using append

In [ ]:
# Combine two arrays only

In [18]:
return_BOC=return_array1[2]
return_BOC

array([ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764])

In [20]:
return_SAIC=return_array1[3]
return_SAIC

array([ 0.021242,  0.002133, -0.029803, -0.002743, -0.014301])

In [21]:
return_2stock=np.append([return_BOC],[return_SAIC],axis=0) # combine by column
return_2stock

array([[ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242,  0.002133, -0.029803, -0.002743, -0.014301]])

In [22]:
return_2stock_new1=np.append([return_BOC],[return_SAIC],axis=1) # combine by row
return_2stock_new1

array([[ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764,  0.021242,
         0.002133, -0.029803, -0.002743, -0.014301]])

In [23]:
return_2stock_new2=np.append([return_BOC],[return_SAIC]) # default:combine by row
return_2stock_new2

array([ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764,  0.021242,
        0.002133, -0.029803, -0.002743, -0.014301])

### Using concatenate

In [ ]:
# Can be used for 2 arrays above

In [24]:
return_CAST=return_array1[0]
return_CAST

array([-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368])

In [25]:
return_CSS=return_array1[1]
return_CSS

array([-0.013892,  0.024334, -0.033758,  0.014622,  0.000128])

In [30]:
return_4stock=np.concatenate(([return_CAST],[return_CSS],[return_BOC],[return_SAIC]), axis=0) # combine by column
return_4stock

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368],
       [-0.013892,  0.024334, -0.033758,  0.014622,  0.000128],
       [ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242,  0.002133, -0.029803, -0.002743, -0.014301]])

In [27]:
return_4stock_new1=np.concatenate(([return_CAST],[return_CSS],[return_BOC],[return_SAIC]), axis=1) # combine by row
return_4stock_new1

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368, -0.013892,
         0.024334, -0.033758,  0.014622,  0.000128,  0.005848, -0.002907,
         0.005831,  0.005797, -0.005764,  0.021242,  0.002133, -0.029803,
        -0.002743, -0.014301]])

In [28]:
return_4stock_new2=np.concatenate(([return_CAST],[return_CSS],[return_BOC],[return_SAIC])) # default:combine by column
return_4stock_new2

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368],
       [-0.013892,  0.024334, -0.033758,  0.014622,  0.000128],
       [ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242,  0.002133, -0.029803, -0.002743, -0.014301]])