In [1]:
##########################################################################
# Created on Sat Otc 24 22:12:35 2021                                    #
# Python for Financial Analysis and Risk Management                      #
# @author: Meng Lipeng (FRM, CFA)                                        #
##########################################################################

# 2.4.1.Intra array operation

## 1.Sum

In [2]:
import numpy as np
return_array1=np.array([[-0.035099,0.017230,-0.003450,-0.024551,0.039368],
                        [-0.013892,0.024334,-0.033758,0.014622,0.000128],
                        [0.005848,-0.002907,0.005831,0.005797,-0.005764],
                        [0.021242,0.002133,-0.029803,-0.002743,-0.014301]])

In [3]:
return_array1.sum(axis=0) # sum by column

array([-0.021901,  0.04079 , -0.06118 , -0.006875,  0.019431])

In [4]:
return_array1.sum(axis=1) # sum by row

array([-0.006502, -0.008566,  0.008805, -0.023472])

In [5]:
return_array1.sum() # sum all elements

-0.029734999999999998

## 2.Product

In [6]:
return_array1.prod(axis=0) # prod by column

array([ 6.05706573e-08, -2.59976845e-09, -2.02394557e-08,  5.70827745e-09,
        4.15378200e-10])

In [7]:
return_array1.prod(axis=1) # prod by row

array([-2.01656235e-09,  2.13585486e-11,  3.31224696e-12, -5.29710348e-11])

In [8]:
return_array1.prod() # prod all elements

7.556915345169367e-42

## 3.Extremum

In [9]:
return_array1.max(axis=0) # max by column

array([0.021242, 0.024334, 0.005831, 0.014622, 0.039368])

In [11]:
return_array1.max(axis=1) # max by row

array([0.039368, 0.024334, 0.005848, 0.021242])

In [10]:
return_array1.max() # max all elements

0.039368

In [12]:
return_array1.min(axis=0) # min by column

array([-0.035099, -0.002907, -0.033758, -0.024551, -0.014301])

In [13]:
return_array1.min(axis=1) # min by row

array([-0.035099, -0.033758, -0.005764, -0.029803])

In [14]:
return_array1.min() # min all elements

-0.035099

## 4.Mean

In [15]:
return_array1.mean(axis=0) # mean by column

array([-0.00547525,  0.0101975 , -0.015295  , -0.00171875,  0.00485775])

In [16]:
return_array1.mean(axis=1) # mean by row

array([-0.0013004, -0.0017132,  0.001761 , -0.0046944])

In [17]:
return_array1.mean() # mean all elements

-0.0014867499999999998

## 5.Variance

In [18]:
return_array1.var(axis=0) # var by column

array([0.00044761, 0.00012152, 0.00028449, 0.00021147, 0.0004233 ])

In [19]:
return_array1.var(axis=1) # var by row

array([7.36970205e-04, 4.24775556e-04, 2.55947228e-05, 2.89169351e-04])

In [20]:
return_array1.var() # var all elements

0.0003743581848875

In [21]:
return_array1.std(axis=0) # std by column

array([0.02115677, 0.01102339, 0.01686695, 0.0145419 , 0.0205743 ])

In [22]:
return_array1.std(axis=1) # std by row

array([0.0271472 , 0.02061008, 0.00505912, 0.01700498])

In [23]:
return_array1.std() # std all elements

0.019348338039415686

## 6.Power

In [24]:
np.sqrt(return_array1) #sqrt every elements

/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/custom_python/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[       nan, 0.13126309,        nan,        nan, 0.19841371],
       [       nan, 0.15599359,        nan, 0.12092146, 0.01131371],
       [0.07647222,        nan, 0.07636098, 0.07613803,        nan],
       [0.14574636, 0.04618441,        nan,        nan,        nan]])

In [25]:
np.square(return_array1) #square every elements

array([[1.23193980e-03, 2.96872900e-04, 1.19025000e-05, 6.02751601e-04,
        1.54983942e-03],
       [1.92987664e-04, 5.92143556e-04, 1.13960256e-03, 2.13802884e-04,
        1.63840000e-08],
       [3.41991040e-05, 8.45064900e-06, 3.40005610e-05, 3.36052090e-05,
        3.32236960e-05],
       [4.51222564e-04, 4.54968900e-06, 8.88218809e-04, 7.52404900e-06,
        2.04518601e-04]])

In [26]:
np.exp(return_array1) #exp every elements

array([[0.96550983, 1.01737929, 0.99655594, 0.97574792, 1.04015319],
       [0.98620405, 1.02463249, 0.96680544, 1.01472942, 1.00012801],
       [1.00586513, 0.99709722, 1.00584803, 1.00581384, 0.99425258],
       [1.02146922, 1.00213528, 0.97063673, 0.99726076, 0.98580077]])

## 7.Log

In [27]:
np.log(return_array1) #ln(x)

/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/custom_python/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[        nan, -4.06110323,         nan,         nan, -3.23480198],
       [        nan, -3.71588073,         nan, -4.22522804, -8.96348029],
       [-5.14165556,         nan, -5.14456677, -5.15041474,         nan],
       [-3.85177493, -6.15022584,         nan,         nan,         nan]])

In [28]:
np.log2(return_array1) #log2(x)

/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/custom_python/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([[         nan,  -5.85893349,          nan,          nan,
         -4.66683277],
       [         nan,  -5.3608827 ,          nan,  -6.09571553,
        -12.93156857],
       [ -7.41784097,          nan,  -7.42204096,  -7.4304778 ,
                 nan],
       [ -5.55693658,  -8.87290032,          nan,          nan,
                 nan]])

In [29]:
np.log10(return_array1) #log10(x)

/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/custom_python/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([[        nan, -1.76371472,         nan,         nan, -1.40485665],
       [        nan, -1.6137865 ,         nan, -1.83499322, -3.89279003],
       [-2.23299264,         nan, -2.23425696, -2.2367967 ,         nan],
       [-1.6728046 , -2.67100914,         nan,         nan,         nan]])

In [30]:
np.log1p(return_array1) #ln(1+x)

array([[-0.03572977,  0.01708325, -0.00345596, -0.0248574 ,  0.03861284],
       [-0.0139894 ,  0.02404265, -0.03434096,  0.01451613,  0.00012799],
       [ 0.00583097, -0.00291123,  0.00581407,  0.00578026, -0.00578068],
       [ 0.02101953,  0.00213073, -0.03025614, -0.00274677, -0.01440424]])

# 2.4.2.Inter array operation

In [31]:
one_return=np.ones_like(return_array1)
one_return

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
new_array1=return_array1+one_return #sum 2-dim array
new_array1

array([[0.964901, 1.01723 , 0.99655 , 0.975449, 1.039368],
       [0.986108, 1.024334, 0.966242, 1.014622, 1.000128],
       [1.005848, 0.997093, 1.005831, 1.005797, 0.994236],
       [1.021242, 1.002133, 0.970197, 0.997257, 0.985699]])

In [33]:
new_array2=return_array1-one_return #minus 2-dim array
new_array2

array([[-1.035099, -0.98277 , -1.00345 , -1.024551, -0.960632],
       [-1.013892, -0.975666, -1.033758, -0.985378, -0.999872],
       [-0.994152, -1.002907, -0.994169, -0.994203, -1.005764],
       [-0.978758, -0.997867, -1.029803, -1.002743, -1.014301]])

In [34]:
new_array3=new_array1*new_array2 #multiple 2-dim array
new_array3

array([[-0.99876806, -0.99970313, -0.9999881 , -0.99939725, -0.99845016],
       [-0.99980701, -0.99940786, -0.9988604 , -0.9997862 , -0.99999998],
       [-0.9999658 , -0.99999155, -0.999966  , -0.99996639, -0.99996678],
       [-0.99954878, -0.99999545, -0.99911178, -0.99999248, -0.99979548]])

In [35]:
new_array4=new_array1/new_array2 #divide 2-dim array
new_array4

array([[-0.93218233, -1.03506416, -0.99312372, -0.95207462, -1.08196271],
       [-0.97259669, -1.04988182, -0.93468878, -1.02967795, -1.00025603],
       [-1.0117648 , -0.99420285, -1.0117304 , -1.0116616 , -0.98853807],
       [-1.04340603, -1.00427512, -0.94211903, -0.99452901, -0.97180127]])

In [36]:
new_array5=new_array1**new_array2 #pow 2-dim array
new_array5

array([[1.03767627, 0.98335125, 1.00347391, 1.02579475, 0.96358678],
       [1.0142848 , 0.9768154 , 1.0361379 , 0.98579794, 0.99987203],
       [0.9942199 , 1.00292396, 0.99423651, 0.99426973, 1.00583093],
       [0.97963714, 0.99787608, 1.03164835, 1.0027581 , 1.01471749]])

In [37]:
new_array6=pow(new_array1,new_array2) #pow 2-dim array using pow function
new_array6

array([[1.03767627, 0.98335125, 1.00347391, 1.02579475, 0.96358678],
       [1.0142848 , 0.9768154 , 1.0361379 , 0.98579794, 0.99987203],
       [0.9942199 , 1.00292396, 0.99423651, 0.99426973, 1.00583093],
       [0.97963714, 0.99787608, 1.03164835, 1.0027581 , 1.01471749]])

In [38]:
new_array7=new_array6+np.array([1,0,1,0,1]) #add 2-dim array with 1-dim array
new_array7

array([[2.03767627, 0.98335125, 2.00347391, 1.02579475, 1.96358678],
       [2.0142848 , 0.9768154 , 2.0361379 , 0.98579794, 1.99987203],
       [1.9942199 , 1.00292396, 1.99423651, 0.99426973, 2.00583093],
       [1.97963714, 0.99787608, 2.03164835, 1.0027581 , 2.01471749]])

In [39]:
new_array8=return_array1+1 #plus 1 with all elements
new_array8

array([[0.964901, 1.01723 , 0.99655 , 0.975449, 1.039368],
       [0.986108, 1.024334, 0.966242, 1.014622, 1.000128],
       [1.005848, 0.997093, 1.005831, 1.005797, 0.994236],
       [1.021242, 1.002133, 0.970197, 0.997257, 0.985699]])

In [40]:
new_array9=return_array1-1 #minus 1 with all elements
new_array9

array([[-1.035099, -0.98277 , -1.00345 , -1.024551, -0.960632],
       [-1.013892, -0.975666, -1.033758, -0.985378, -0.999872],
       [-0.994152, -1.002907, -0.994169, -0.994203, -1.005764],
       [-0.978758, -0.997867, -1.029803, -1.002743, -1.014301]])

In [41]:
new_array10=return_array1*2 #multiple 2 with all elements
new_array10

array([[-0.070198,  0.03446 , -0.0069  , -0.049102,  0.078736],
       [-0.027784,  0.048668, -0.067516,  0.029244,  0.000256],
       [ 0.011696, -0.005814,  0.011662,  0.011594, -0.011528],
       [ 0.042484,  0.004266, -0.059606, -0.005486, -0.028602]])

In [42]:
new_array11=return_array1/2 #divide 2 with all elements
new_array11

array([[-1.75495e-02,  8.61500e-03, -1.72500e-03, -1.22755e-02,
         1.96840e-02],
       [-6.94600e-03,  1.21670e-02, -1.68790e-02,  7.31100e-03,
         6.40000e-05],
       [ 2.92400e-03, -1.45350e-03,  2.91550e-03,  2.89850e-03,
        -2.88200e-03],
       [ 1.06210e-02,  1.06650e-03, -1.49015e-02, -1.37150e-03,
        -7.15050e-03]])

In [43]:
new_array12=return_array1**2 #square all elements
new_array12

array([[1.23193980e-03, 2.96872900e-04, 1.19025000e-05, 6.02751601e-04,
        1.54983942e-03],
       [1.92987664e-04, 5.92143556e-04, 1.13960256e-03, 2.13802884e-04,
        1.63840000e-08],
       [3.41991040e-05, 8.45064900e-06, 3.40005610e-05, 3.36052090e-05,
        3.32236960e-05],
       [4.51222564e-04, 4.54968900e-06, 8.88218809e-04, 7.52404900e-06,
        2.04518601e-04]])

In [45]:
new_array13=pow(return_array1,2) #square all elements using pow function
new_array13

array([[1.23193980e-03, 2.96872900e-04, 1.19025000e-05, 6.02751601e-04,
        1.54983942e-03],
       [1.92987664e-04, 5.92143556e-04, 1.13960256e-03, 2.13802884e-04,
        1.63840000e-08],
       [3.41991040e-05, 8.45064900e-06, 3.40005610e-05, 3.36052090e-05,
        3.32236960e-05],
       [4.51222564e-04, 4.54968900e-06, 8.88218809e-04, 7.52404900e-06,
        2.04518601e-04]])

In [46]:
zero_return=np.zeros_like(return_array1)
zero_return

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
return_max=np.maximum(return_array1,zero_return)
return_max

array([[0.      , 0.01723 , 0.      , 0.      , 0.039368],
       [0.      , 0.024334, 0.      , 0.014622, 0.000128],
       [0.005848, 0.      , 0.005831, 0.005797, 0.      ],
       [0.021242, 0.002133, 0.      , 0.      , 0.      ]])

In [48]:
return_min=np.minimum(return_array1,zero_return)
return_min

array([[-0.035099,  0.      , -0.00345 , -0.024551,  0.      ],
       [-0.013892,  0.      , -0.033758,  0.      ,  0.      ],
       [ 0.      , -0.002907,  0.      ,  0.      , -0.005764],
       [ 0.      ,  0.      , -0.029803, -0.002743, -0.014301]])

# 2.4.3.Matrix

## 1.Calculate properties of matrix

In [49]:
corr_return=np.corrcoef(return_array1) #calculate correlation coefficient
corr_return

array([[ 1.        ,  0.235297  , -0.92216137, -0.49050709],
       [ 0.235297  ,  1.        , -0.47897595,  0.38847344],
       [-0.92216137, -0.47897595,  1.        ,  0.12113241],
       [-0.49050709,  0.38847344,  0.12113241,  1.        ]])

In [50]:
np.diag(corr_return) #diagonal line

array([1., 1., 1., 1.])

In [51]:
np.triu(corr_return) #upper triangular

array([[ 1.        ,  0.235297  , -0.92216137, -0.49050709],
       [ 0.        ,  1.        , -0.47897595,  0.38847344],
       [ 0.        ,  0.        ,  1.        ,  0.12113241],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [52]:
np.tril(corr_return) #lower triangular

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.235297  ,  1.        ,  0.        ,  0.        ],
       [-0.92216137, -0.47897595,  1.        ,  0.        ],
       [-0.49050709,  0.38847344,  0.12113241,  1.        ]])

In [53]:
np.trace(corr_return) #sum diagonal line

4.0

In [54]:
np.transpose(return_array1) #transpose

array([[-0.035099, -0.013892,  0.005848,  0.021242],
       [ 0.01723 ,  0.024334, -0.002907,  0.002133],
       [-0.00345 , -0.033758,  0.005831, -0.029803],
       [-0.024551,  0.014622,  0.005797, -0.002743],
       [ 0.039368,  0.000128, -0.005764, -0.014301]])

In [55]:
return_array1.T #transpose

array([[-0.035099, -0.013892,  0.005848,  0.021242],
       [ 0.01723 ,  0.024334, -0.002907,  0.002133],
       [-0.00345 , -0.033758,  0.005831, -0.029803],
       [-0.024551,  0.014622,  0.005797, -0.002743],
       [ 0.039368,  0.000128, -0.005764, -0.014301]])

## 2.Operations of matrix

In [57]:
weight_array1=np.array([0.15, 0.2, 0.25, 0.4])

In [58]:
# Inner product
return_daily=np.dot(weight_array1, return_array1) #Daily return of portfolio
return_daily

array([ 0.00191555,  0.00757775, -0.01773255, -0.0004062 , -0.0012306 ])

In [59]:
import numpy.linalg as la # import sub mudule for linear algebra

In [60]:
la.det(corr_return) #determinant of matrix

0.0010443476095574008

In [61]:
la.inv(corr_return) #inverse matrix

array([[536.14264022,  32.78083187, 486.94315285, 191.26268821],
       [ 32.78083187,   3.76405157,  30.71215642,  10.89675899],
       [486.94315285,  30.71215642, 443.77493714, 173.16268611],
       [191.26268821,  10.89675899, 173.16268611,  69.60699042]])

In [64]:
I=np.dot(la.inv(corr_return),corr_return) #inner product of matrix and its inverse matrix is an identity matrix
I.round(4)

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0., -0.],
       [ 0.,  0.,  1., -0.],
       [-0.,  0., -0.,  1.]])

In [65]:
la.eig(corr_return) #eigenvalue: first array is eigenvalue and second array is eigenvector

(array([2.20179755e+00, 1.45527819e+00, 9.53086174e-04, 3.41971177e-01]),
 array([[ 0.65379828,  0.182798  , -0.71463557,  0.16860816],
        [ 0.31198733, -0.65501986, -0.0441565 , -0.68677732],
        [-0.64934186,  0.12672681, -0.64990211, -0.37406244],
        [-0.23144518, -0.7221317 , -0.25489892,  0.5999879 ]]))

In [66]:
la.svd(corr_return) #sigular value decomposition: first and third array are unitary matrix, second array is singular value

(array([[-0.65379828,  0.182798  ,  0.16860816,  0.71463557],
        [-0.31198733, -0.65501986, -0.68677732,  0.0441565 ],
        [ 0.64934186,  0.12672681, -0.37406244,  0.64990211],
        [ 0.23144518, -0.7221317 ,  0.5999879 ,  0.25489892]]),
 array([2.20179755e+00, 1.45527819e+00, 3.41971177e-01, 9.53086174e-04]),
 array([[-0.65379828, -0.31198733,  0.64934186,  0.23144518],
        [ 0.182798  , -0.65501986,  0.12672681, -0.7221317 ],
        [ 0.16860816, -0.68677732, -0.37406244,  0.5999879 ],
        [ 0.71463557,  0.0441565 ,  0.64990211,  0.25489892]]))