In [1]:
##########################################################################
# Created on Sat Otc 25 21:37:45 2021                                    #
# Python for Financial Analysis and Risk Management                      #
# @author: Meng Lipeng (FRM, CFA)                                        #
##########################################################################

In [2]:
import numpy_financial as npf
npf.__version__

'1.0.0'

# 2.6.1.Future value

In [7]:
V0=2e7
V1=3e6
T=5
r=0.08

In [8]:
FV1=npf.fv(rate=r,nper=T,pmt=-V1,pv=-V0,when='end')
print('FV(when payment occurred at the end of year): ',round(FV1,2))

FV(when payment occurred at the end of year):  46986364.42


In [9]:
FV2=npf.fv(rate=r,nper=T,pmt=-V1,pv=-V0,when='begin')
print('FV(when payment occurred at the beginning of year): ',round(FV2,2))

FV(when payment occurred at the beginning of year):  48394348.65


In [10]:
FV_diff=FV2-FV1
print('Difference: ',round(FV_diff,2))

Difference:  1407984.23


In [13]:
3e6*(1+r)**5-3e6

1407984.2304000016

# 2.6.2.Present value

In [15]:
V1=2e6
Vt=2.5e7
T=6
r=0.06

In [17]:
PV1=npf.pv(rate=r,nper=T,pmt=V1,fv=Vt,when=0)
print('PV(when payment occurred at the end of year): ',round(PV1,2))

PV(when payment occurred at the end of year):  -27458662.16


In [18]:
PV2=npf.pv(rate=r,nper=T,pmt=V1,fv=Vt,when=1)
print('PV(when payment occurred at the beginning of year): ',round(PV2,2))

PV(when payment occurred at the beginning of year):  -28048741.08


In [19]:
PV_diff=PV2-PV1
print('Diffenence: ',round(PV_diff,2))

Diffenence:  -590078.92


# 2.6.3.NPV and IRR

## 1.NPV(Net Present Value)

In [23]:
import numpy as np
R1=0.09 #required return
cashflow=np.array([-2.8e7,7e6,8e6,9e6,1e7])

In [24]:
NPV1=npf.npv(rate=R1,values=cashflow)
print('NPV: ',round(NPV1,2))

NPV:  -810638.27


In [25]:
R2=0.06
NPV2=npf.npv(rate=R2,values=cashflow)
print('NPV: ',round(NPV2,2))

NPV:  1201255.28


## 2.IRR(Internal Rate of Return)

In [26]:
IRR=npf.irr(values=cashflow)
print('IRR: ',round(IRR,6))

IRR:  0.077503


# 2.6.4.Payment of mortgage loan

In [28]:
prin_loan=5e6
tenor_loan=5*12
rate_loan=0.06/12

In [29]:
payment=npf.pmt(rate=rate_loan,nper=tenor_loan,pv=prin_loan,fv=0,when='end')
print('Monthly payment: ',round(payment,2))

Monthly payment:  -96664.01


In [36]:
tenor_list=np.arange(tenor_loan)+1

In [37]:
payment_interst=npf.ipmt(rate=rate_loan,per=tenor_list,nper=tenor_loan,pv=prin_loan,fv=0,when='end')
payment_interst

array([-25000.        , -24641.67996176, -24281.56832334, -23919.65612672,
       -23555.93436912, -23190.39400273, -22823.0259345 , -22453.82102594,
       -22082.77009283, -21709.86390506, -21335.09318635, -20958.44861405,
       -20579.92081888, -20199.50038474, -19817.17784843, -19432.94369944,
       -19046.7883797 , -18658.70228336, -18268.67575654, -17876.69909709,
       -17482.76255434, -17086.85632887, -16688.97057228, -16289.09538691,
       -15887.22082561, -15483.3368915 , -15077.43353772, -14669.50066718,
       -14259.52813228, -13847.5057347 , -13433.42322514, -13017.27030303,
       -12599.03661631, -12178.71176115, -11756.28528172, -11331.7466699 ,
       -10905.08536501, -10476.2907536 , -10045.35216913,  -9612.25889174,
        -9177.00014797,  -8739.56511047,  -8299.94289779,  -7858.12257404,
        -7414.09314867,  -6967.84357618,  -6519.36275583,  -6068.63953137,
        -5615.66269079,  -5160.42096601,  -4702.9030326 ,  -4243.09750953,
        -3780.99295884,  

In [38]:
payment_principle=npf.ppmt(rate=rate_loan,per=tenor_list,nper=tenor_loan,pv=prin_loan,fv=0,when='end')
payment_principle

array([-71664.00764714, -72022.32768538, -72382.4393238 , -72744.35152042,
       -73108.07327803, -73473.61364442, -73840.98171264, -74210.1866212 ,
       -74581.23755431, -74954.14374208, -75328.91446079, -75705.55903309,
       -76084.08682826, -76464.5072624 , -76846.82979871, -77231.0639477 ,
       -77617.21926744, -78005.30536378, -78395.3318906 , -78787.30855005,
       -79181.2450928 , -79577.15131827, -79975.03707486, -80374.91226023,
       -80776.78682153, -81180.67075564, -81586.57410942, -81994.50697997,
       -82404.47951487, -82816.50191244, -83230.584422  , -83646.73734411,
       -84064.97103083, -84485.29588599, -84907.72236542, -85332.26097724,
       -85758.92228213, -86187.71689354, -86618.65547801, -87051.7487554 ,
       -87487.00749918, -87924.44253667, -88364.06474935, -88805.8850731 ,
       -89249.91449847, -89696.16407096, -90144.64489131, -90595.36811577,
       -91048.34495635, -91503.58668113, -91961.10461454, -92420.91013761,
       -92883.0146883 , -

In [39]:
(payment_interst+payment_principle).round(2)

array([-96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01,
       -96664.01, -96664.01, -96664.01, -96664.01, -96664.01, -96664.01])